---
comments: false
---

# Contributing

We welcome improvements to this publication! If you'd like to improve or extend the publication, please submit a pull request. We'll collaborate with you to incorporate your revisions.

* Did you spot any mistakes?
* Do you think an analysis is missing?
* Do you think the wording could be improved?
* Did you spot a typo or grammatical mistake?

These are just a few examples of revisions that we'd be happy to receive from you.

::: {.callout-note}
To learn about how we credit external collaborators, click [here](https://github.com/Arcadia-Science/arcadia-software-handbook/blob/main/guides-and-standards/guide--credit-for-contributions.md).
:::

## Getting started

If you haven't already, follow our [setup guide](SETUP.qmd) to create a local copy of the code and compute environment.

## Snapshot current version

Before making any changes, we need to preserve the current state of the publication by creating a versioned snapshot. This ensures we maintain an archive of all previous versions alongside the latest one. To create this snapshot, run:

```bash
make bump-version
```

Commit the changes and untracked files (`_freeze/*`, `_quarto.yml`, `index_*.ipynb`) introduced by this version snapshot before proceeding with your changes.

## Make your changes

Edit `index.ipynb` to your liking.

## Steps before publishing

To publish your revisions, we need you to open a pull request. And in order for us to merge your pull request, here's what we'll need from you in addition to your content changes.

Begin with a clean branch (no uncommitted changes). Then run the notebook from the command line:

```bash
make execute
```

This command will update `index.ipynb` with the latest execution results. Importantly, it may generate runtime artifacts in the `_freeze/` directory.

Then run `make preview` to see how the publication is rendering. Verify that your changes appear how you intend them to appear. If not, make the necessary changes and re-run `make execute`.

Once happy, commit `index.ipynb` and all files in the `_freeze/` directory.

Finally, submit a pull request and we'll work with you to merge the changes.

Once we approve your pull request, we'll merge your changes and notify you when they go live at the [hosted URL](https://{{< var pub.org >}}.github.io/{{< var pub.repo >}}/). Thanks for contributing!
